SUM-34 SUM-36 | @rebeccahongsf | theme and style top banner and banner
SU-SWS/summer-nextjs pull request #16
Opened 2024-06-14 15:46 UTC by rebeccahongsf

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2024-06-20 23:09 UTC, rebeccahongsf commented on src/components/paragraphs/sum-top-banner/sum-top-banner-paragraph.tsx
> +              // className={}
As soon as https://github.com/SU-SWS/ace-stanfordlagunita/pull/124 is merged in, I'll circle back to this and make the transparent card adjustments 😄

2024-06-21 15:22 UTC, pookmish requested changes

2024-06-21 15:22 UTC, pookmish commented on src/components/paragraphs/sum-top-banner/sum-top-banner-paragraph.tsx
> +  const bgColor = behaviors.sum_banner_behaviors?.sum_banner_overlay_bkg || "olive"
This doesn't work. It should be `behaviors?.sum_top_banner_behavior?.sum_top_banner_overlay_bkg`

2024-06-21 15:22 UTC, pookmish commented on src/components/paragraphs/sum-top-banner/sum-top-banner-paragraph.tsx
>          overlayPosition={behaviors.hero_pattern?.overlay_position}
This should be `behaviors?.sum_top_banner_behavior?.sum_top_banner_alignment || "right"`

2024-06-21 15:22 UTC, pookmish commented on src/components/paragraphs/stanford-banner/banner-paragraph.tsx
> +            "bg-spirited-dark": bgColor === "spirited_dark",
With spirited dark, we need to use `text-white`. Even `text-black-true` fail contrast ratio.

2024-06-21 15:22 UTC, pookmish commented on src/components/paragraphs/sum-top-banner/sum-top-banner-paragraph.tsx
> +          "bg-spirited-dark": bgColor === "spirited_dark",
With spirited dark, we need to use `text-white`. Even `text-black-true` fail contrast ratio.

2024-06-21 15:22 UTC, pookmish commented on src/components/paragraphs/sum-top-banner/sum-top-banner-paragraph.tsx
> +        cardColorClasses={clsx("mb-0 border border-white border-b-0 border-x-0 border-b-4 lg:border-x-4 lg:border-y-0 bg-poppy-light",
`bg-poppy-light` doesn't work. This looks to be an issue from the BE.

2024-06-21 15:22 UTC, pookmish commented on src/components/paragraphs/stanford-banner/banner-paragraph.tsx
> +import clsx from "clsx";
Looks like prettier isn't doing what it's supposed to. make sure to run `yarn install` if you merge/update to 1.x branch.

2024-06-21 15:45 UTC, pookmish commented on src/components/paragraphs/sum-top-banner/sum-top-banner-paragraph.tsx
> +        cardColorClasses={clsx("mb-0 border border-white border-b-0 border-x-0 border-b-4 lg:border-x-4 lg:border-y-0 bg-poppy-light",
Oh nvm, it's because you are defaulting to olive above.

2024-06-21 15:46 UTC, pookmish commented on src/components/paragraphs/sum-top-banner/sum-top-banner-paragraph.tsx
> +  const bgColor = behaviors.sum_banner_behaviors?.sum_banner_overlay_bkg || "olive"
Default to poppy light, not olive.

2024-06-26 15:21 UTC, pookmish requested changes

2024-06-27 21:57 UTC, pookmish approved these changes
Looks good

2024-06-27 21:57 UTC, merged