SUM-173 | theme and style calculator page
SU-SWS/summer-nextjs pull request #20
Opened 2024-06-28 16:11 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Theme and style calculator page

# Review By (Date)
- When possible

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Spin up local
3. Navigate to calculator page `/cost/tuition-fees-calculator`
4. Verify that the calculator components match the [figma mock](https://www.figma.com/design/vnc2oxvzX9qZ3rK5vmjpdZ/Summer-Session-Wireframes?node-id=4590-36334&t=CXo9bzAx343NnWRc-1) for desktop and responsive
5. Review code 👾 

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? **Nope**

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

# Associated Issues and/or People
- SUM-173

2024-07-02 16:08 UTC, pookmish requested changes
Can you review the mobile view of the calculator. It looks like the sticky summery is floating in the middle for some reason. Screen 400x673
![image](https://github.com/SU-SWS/summer-nextjs/assets/7185045/1c75190b-7f65-49a1-b793-d7363a24397f)

2024-07-03 00:03 UTC, rebeccahongsf commented
> Can you review the mobile view of the calculator. It looks like the sticky summery is floating in the middle for some reason. Screen 400x673 ![image](https://private-user-images.githubusercontent.com/7185045/345110643-1c75190b-7f65-49a1-b793-d7363a24397f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjM3MDAsIm5iZiI6MTcxOTk2MzQwMCwicGF0aCI6Ii83MTg1MDQ1LzM0NTExMDY0My0xYzc1MTkwYi03ZjY1LTQ5YTEtYjc5My1kNzM2M2EyNDM5N2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMjMzNjQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdjYWIzNjY2NjcwZjYwN2I4YWZjN2U0NzRhYTFmZmU0NGFkYjJhODNhM2M2NjlhZDI3OWExNjViNzVlY2NkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BVT6os37HLRynJmSsTCITDuaiAiVrbQKSwMrb_i2bkw)

@pookmish I cannot seem to reproduce it on Chrome. 
<img width="499" alt="image" src="https://github.com/SU-SWS/summer-nextjs/assets/34019925/0b336b6e-6a71-491f-b557-7d620c95161b">


What device/browser are you previewing on? 😃

2024-07-03 16:33 UTC, pookmish commented
Looks like it was just due to something in the local footer. I'll make a commit and this will be g2g

2024-07-03 16:34 UTC, pookmish approved these changes

2024-07-03 16:38 UTC, merged